server:
  port: 8082
spring:
  application:
    name: user-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/demo-realm
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

keycloak:
  server-url: http://localhost:8080
  realm: demo-realm
  client-id: gateway-client
  client-secret: leuDC81GnBf7githks8Swl5IaxWT2Y66
  admin-username: admin
  admin-password: admin


logging:
  level:
    root: INFO
    com.project.gateway: DEBUG